### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ocxs**
Add some queston-links

### CODE REVIEW

**Comment by pezy** [comment]
Thx for your contribution. :+1:

**Comment by Mooophy** [comment]
To be honest, I don't think it's a good idea to quote answers from zhihu.com. The first reason is that ZHIHU is not a professional programmer site. Secondly, and more importantly, we should not limit repo to Chinese speakers.

**Comment by pezy** [comment]
@Mooophy  Second. I will modify it later.

**Comment by Mooophy** [comment]
@pezy Sweet.

**Comment by Ocxs** [comment]
@pezy  You can remove answers that quoted  from Chinese website to [C++ Primer issues(豆瓣讨论组)](http://www.douban.com/group/532124/ ) :smile:

**Comment by pezy** [comment]
@Ocxs Orz... 

Sorry for this and thanks for your action.... :disappointed: 

> You can remove answers that quoted from Chinese website

In addition to the HOME page, have any answer quoted it? (If really, maybe I should remove too...)

**Comment by Ocxs** [comment]
@pezy It doesn't matter ! :smile:  No, I haven't . :coffee:

**Comment by pezy** [comment]
@Ocxs  thx for understanding. :sweat_smile:

**Pull request merged**
